#!/bin/bash

SCRIPTSDIR=$HOME/.config/hypr/scripts

# Kill already running processes
_ps=(waybar mako swaybg)
for _prs in "${_ps[@]}"; do
    if [[ $(pidof ${_prs}) ]]; then
        killall -9 ${_prs}
    fi
done

# polkit agent
if [[ ! 'pidof polkit-gnome-authentication-agent-1' ]]; then
    /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
fi

# Apply themes
${SCRIPTSDIR}/gtkThemes &

# Launch notifications daemon
${SCRIPTSDIR}/notifications &

# Launch the wallpaper changer
${SCRIPTSDIR}/changeWall &

# Launch some useful software
nm-applet --indicator &
hyprsunset -t 3700 &
